name: 'buildinpublic.so Action Export'
description: 'Export your commits to buildinpublic.so to track your building in public journey'
author: 'eddspire'

branding:
  icon: 'upload-cloud'
  color: 'blue'

inputs:
  api-token:
    description: 'API token for buildinpublic.so'
    required: true
  github-token:
    description: 'GitHub token for API access (defaults to GITHUB_TOKEN)'
    required: false

outputs:
  commits:
    description: 'Number of commits processed'

runs:
  using: 'node20'
  main: 'dist/index.js' 